version: '3.9'

services:
  exogena_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - db_data:/app/data
    environment:
      - EXOGENA_DB_PATH=/app/data/app.db

volumes:
  db_data:
